---
title: "group project"
format: html
editor: visual
---

```{r}
# how to load the data
# data_obj <- "https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9e123f84-ce0d-4094-b898-c9e73680eafa"
# path <- "~/api-practice"
# 
# download_d1_data(data_obj,
#                  path)
```

### Load in Data from EDI

```{r}
library(tidyverse)
library(metajam)
library(lubridate)
library(tidyquant)
```

```{r}
## loaded data into group project folder

#Q1_data <- "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-luq.20.4923061&entityid=96e0ef7b3f2bc92485a559645d545845"
#Q2_data <-"https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-luq.20.4923061&entityid=8d1e2d357a2dc2d56b9eedea56a46236"
#Q3_data <- "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-luq.20.4923061&entityid=665f37efee3109a7c3aff95e079e2de2"
#RPM_data <- "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-luq.20.4923061&entityid=acb18d969cf36e7efda2604a1449e816"

#path <- "/courses/EDS214/group_project/team_siguana"

#download_d1_data(Q1_data, path)
#download_d1_data(Q2_data, path)
#download_d1_data(Q3_data, path)
#download_d1_data(RPM_data, path)
```

# Reading in the Water Chemistry Stream Data

```{r}
#Reading in all datasets into a list
q1_data <- read_d1_files("/courses/EDS214/group_project/team_siguana/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq_20_4923061__QuebradaCuenca1-Bisley__csv")
q2_data <- read_d1_files("/courses/EDS214/group_project/team_siguana/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq_20_4923061__QuebradaCuenca2-Bisley__csv")
q3_data <- read_d1_files("/courses/EDS214/group_project/team_siguana/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq_20_4923061__QuebradaCuenca3-Bisley__csv")
prm <- read_d1_files("/courses/EDS214/group_project/team_siguana/__RioMameyesPuenteRoto__csv")

#Make the data into dataframes
q1_data_df <- q1_data$data
q2_data_df <- q2_data$data
q3_data_df <- q3_data$data
prm_data <- prm$data

q1_attribute_metadata <- q1_data$attribute_metadata
```

## Data for Remaking Graph

```{r}
# select columns of interest: K, NO3-N, Sample_Date, Sample_ID
hugo_data <- q1_data_df %>% 
  full_join(q2_data_df) %>% 
  full_join(q3_data_df) %>% 
  full_join(prm_data) %>% 
  select(Sample_ID, Sample_Date, K, `NO3-N`)
```

## Plot

```{r}
# Wrangling data for plot 
hugo_plot <- hugo_data %>% 
  pivot_longer(cols = c(3,4)) %>% 
  mutate(year = as.numeric(format(Sample_Date,'%Y'))) %>% 
  filter(year %in% c(1988:1995))

# Remaking the plot
ggplot(hugo_plot, aes(Sample_Date, value, color = Sample_ID, linetype = "solid")) +
  #geom_line(aes(color = Sample_ID)) +
  geom_ma(inherit.aes = TRUE, na.rm = TRUE, ma_fun = SMA, n = 63) + # include moving averages instead of geom_line
  facet_wrap(~name, 
             scales =  "free", 
             ncol = 1,  
             strip.position = "left",  
             labeller = as_labeller(c("NO3-N" = "NO3-N ug/L", "K" = "K mg/L"))) + 
  labs(title = "Chemical concentrations in streams", 
       x = "Year",
       y = "", 
       color = "Site") +
  scale_color_manual(breaks = c("MPR", "Q1", "Q2", "Q3"),
                        values=c("gray48", "cornflowerblue", "pink", "palegreen3")) +
  theme_minimal() +
  geom_vline(xintercept = as.numeric(as.Date("1989-09-09")), 
             linetype=4) +
  theme(plot.title = element_text(face="bold", size = 14)) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.text = element_text(face = "bold", size = 10))
```

Goal \# 2:

```{r}
#Let's read in the basic stream data 

maria_data_obj <- "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-luq.20.4923061&entityid=ef01a691d7915bb3a8d6b0b69dc2b4ba"
path <- "/courses/EDS214/group_project/team_siguana"

download_d1_data(maria_data_obj,
                 path)
```

```{r}
maria_data <- read_d1_files("/courses/EDS214/group_project/team_siguana/https_pasta.lternet.edu_package_metadata_eml_knb-lter-luq_20_4923061__BasicFieldData-Streams__csv")

maria_data_df <- maria_data$data
```

```{r}
#Now let's create a subset of the data to just filter for our dates of interest. In this case it is for the years 2015 - 2018.
maria_data_subset_test <- maria_data_df %>% 
  mutate(Date = lubridate::mdy_hm(Sample_Date)) %>% 
  mutate(Year = lubridate::year(Date)) %>% 
  filter(Year == 2018 | Year == 2017 | Year == 2016 | Year == 2015, Sample_ID == "Q1" | Sample_ID == "Q2" | Sample_ID == "Q3") %>% 
  select(-Code, -Sample_Date, -Sample_Time, -Cond)

```

```{r}
#Now we are going to graph the data:
maria_data_subset_test %>% 
ggplot(aes(x= Date, y = Temp)) + geom_point(aes(color = Sample_ID)) +
  theme_minimal() +
  geom_vline(aes(xintercept = as.numeric(as.POSIXct("2018-10-10"))),linetype = 4) +
  annotate("text", x= as.POSIXct("2018-09-10"), y=22, label="Hurricane Maria", angle=90) +
  labs(title = "Stream Temperature Fluctuation During Hurricane Season", 
       x = "Year",
       y = "Temperature") +
  guides(color=guide_legend("Site:")) +
  theme(plot.title = element_text(face="bold", size = 14)) +
  theme(axis.title = element_text(face = "bold")) +
  theme(strip.text = element_text(face = "bold", size = 10)) 



```
